// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;
namespace ws.winx.editor.extensions
{
	public class AssetModificationProcessorEventDispatcher:AssetModificationProcessor
	{


		// A delegate type for hooking up change notifications.
		public delegate void WillSaveAssetsEventHandler(string[] paths);
		// An event that clients can use to be notified whenever the
		// elements of the list change.
		public static event WillSaveAssetsEventHandler WillSaveAssets;


		static string[] OnWillSaveAssets( string[] paths ) {


			if (WillSaveAssets != null)
						WillSaveAssets (paths);

			return paths;
		}
	}
}

