// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using System.Collections;
using UnityEngine;


namespace ws.winx.editor.utilities
{
	public static class AssetDatabaseUtility
	{

		public static string AbsoluteUrlToAssets(string absoluteUrl)
		{
			Uri fullPath = new Uri (absoluteUrl, UriKind.Absolute);
			Uri relRoot = new Uri (Application.dataPath, UriKind.Absolute);
			
			return relRoot.MakeRelativeUri (fullPath).ToString ();
			
			
		}
	}
}

