// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using BehaviourMachine;
using UnityEngine;


namespace ws.winx.bmachine.extensions
{
		[NodeInfo ( category = "Extensions/Mecanim/", icon = "StateMachine")]
		public class SendEventNormalized:ActionNode
		{
			//
			// Fields
			//

			Animator _animator;
			float _timeNormalizedLast;
			
			[VariableInfo (requiredField = true,tooltip = "The event to send")]
			public FsmEvent eventToSend;
			
			[VariableInfo (requiredField = true,fixedType=true, tooltip = "Normalized time value from 0 to 1."), Range (0f, 1f)]
			public FloatVar timeNormalized;

			
			public override void Awake ()
			{
				
				_animator = this.self.GetComponent<Animator> ();
			}

			public override void Update ()
			{
				float timeNormalized = _animator.GetNextAnimatorStateInfo (((MecanimNode)this.owner).selectedAnimaStateInfo.layer).normalizedTime;
				timeNormalized = timeNormalized - (int)timeNormalized;

				//base.owner.SendEvent (this.eventToSend.id);
				
				//dispatch event to parent I'm done

					_timeNormalizedLast = timeNormalized;

			//this.tree


			}
			
			public override void Reset ()
			{
				this.eventToSend = new FsmEvent ();
				this.timeNormalized = new ConcreteFloatVar ();
				
			}


			public override string ToString ()
			{
				return string.Format ("[SendEventNormalized]{0} {1}",name,timeNormalized.Value);
			}
		}
}

