// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using ws.winx.csharp.utilities;
using System.Reflection;
using System.Collections.Generic;



namespace ws.winx.editor
{
//		public static class Assert
//		{
//		[System.Diagnostics.Conditional("UNITY_EDITOR")]
//		public static void Log(bool comparison,UnityEngine.Object context,params object[] args) {
//
//
//
//
//			if (!comparison) {
//				
//				string format=String.Empty;
//				int numArgs;
//
//				ParameterInfo[] paramters=(typeof(Assert)).GetMethod("Log").GetParameters();
//
//				numArgs=paramters.Length;
//				for(int i=2;i<numArgs;i++){
//
//					format+=paramters[i].Name+"= {"+i+"}";
//					
//					
//					
//				}
//				
//				Debug.LogFormat(context,format,args);
//
//
//
//				
//			}
//		}
//		
//		[System.Diagnostics.Conditional("UNITY_EDITOR")]
//		public static void TestFormat(bool comparison,UnityEngine.Object context,string format,params object[] args) {
//			if (!comparison) {
//				Debug.LogErrorFormat(context,format,args);
//				Debug.Break();
//				
//			}
//		}
//		
//		
//		[System.Diagnostics.Conditional("UNITY_EDITOR")]
//		public static void Test(bool comparison,UnityEngine.Object context,params object[] args) {
//			if (!comparison) {
//
//				string format=String.Empty;
//				int numArgs;
//
//				MethodBase bas=MethodBase.GetCurrentMethod();
//
//
//			
//				ParameterInfo[] paramters=bas.GetParameters();//(typeof(Assert)).GetMethod("Log").GetParameters();
//				
//				numArgs=paramters.Length;
//				for(int i=2;i<numArgs;i++){
//
//					format+="arg"+(i-1)+"= {"+(i-2)+"} ";
//					
//					
//					
//				}
//				
//				
//				
//				Debug.LogErrorFormat(context,format,args);
//				Debug.Break();
//				
//			}
//		}
//		}





}







