// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;


namespace ws.winx.csharp.extensions
{
	public static class IListExtensions
	{
		public static IList<T> Clone<T>(this IList<T> listToClone) where T: ICloneable
		{
			return listToClone.Select(item => (T)item.Clone()).ToList();
		}
	}
}

