// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;
using BehaviourMachine;
using System.Reflection;



namespace ws.winx.unity{

	[System.Serializable]
	public class CurveProperty:Property
	{


		[SerializeField]
		private CurveWrapperW __curveWrapperW;

	

	






		//
		// Properties
		//
		public Color color {
			get{ return __curveWrapperW.color;}
			set{ __curveWrapperW.color = value;}
		}

		public int id {
			get{ return __curveWrapperW.id;}
			set{ __curveWrapperW.id=value;}
		}

		public AnimationCurve curve {
			get {
				return __curveWrapperW.curve;
			}
			set {
				__curveWrapperW.curve = value;
			}
		}

	
		//public Property property;



		//
		// Constructor
		//
		public CurveProperty()//:base()
		{

			//ScriptableObject.CreateInstance<Property> ();
		}

		public void OnEnable ()
		{
			hideFlags = HideFlags.HideAndDontSave;

			if(__curveWrapperW==null)
				__curveWrapperW= (CurveWrapperW)ScriptableObject.CreateInstance<CurveWrapperW>();


		}

		
		
//		#region IEquatable implementation
//		public bool Equals (CurveProperty other)
//		{
//			if (curveWrapperW.curve == null)
//								return false;
//
//		
//
//			return this.curveWrapperW.id == other.curveWrapperW.id;
//		}
//		#endregion
	}
}

