// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;
using BehaviourMachine;
using System.Reflection;



namespace ws.winx.unity{

	[System.Serializable]
	public class CurveVariable:UnityVariable
	{



	

	






		//
		// Properties
		//
		public Color color;

		

		public AnimationCurve curve;
		

	
		public int id;



		//
		// Constructor
		//
		public CurveVariable()//:base()
		{

			//ScriptableObject.CreateInstance<Property> ();
		}

		public void OnEnable ()
		{
			hideFlags = HideFlags.HideAndDontSave;



		}

		
		

	}
}

