// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace ws.winx.unity
{
		


		public class MecanimNodeBlendParameterAttribute:PropertyAttribute
		{
		   public enum Axis{
			X=0,
			Y=1
			}

		public Axis axis;
		public MecanimNodeBlendParameterAttribute(){

		}

			public MecanimNodeBlendParameterAttribute(Axis a){
			this.axis = a;
			}

		}
}

