// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;


namespace ws.winx.unity{

	[System.Serializable]
	public class MecanimStateInfo:ScriptableObject
	{
		int _hash;


		public int hash;

		//DON"T USE GETTERS/SETTERS 
//		public int hash {
//						get {
//								return _hash;
//						}
//						set {
//								_hash = value;
//						}
//				}
		
		public Motion motion;
		
		public int layer;

		public string[] blendParamsNames;

		public int[] blendParamsIDs; 
	
		
		public GUIContent label;
		


    
		
		
		
	}
}

