// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Reflection;

namespace ws.winx.unity
{
		public class RangeAttributeEx:PropertyAttribute
		{

				//
				// Fields
				//
				float _max = float.NaN;
				float _min = float.NaN;
				bool _enabled;
				bool _hasEnableToggle;
				string _fieldNameMax;
				string _fieldNameMin;
				FieldInfo _fieldMaxInfo;
				FieldInfo _fieldMinInfo;
				string _fieldNameEnabled;
				FieldInfo _fieldEnabledInfo;

				public float Max {
						get {

								if (float.IsNaN (_max)) {
										if (serializedObject != null) {
												if (_fieldMaxInfo == null)
														_fieldMaxInfo = this.serializedObject.GetType ().GetField (this._fieldNameMax);

												return (float)_fieldMaxInfo.GetValue (serializedObject);
										}
										return 1.0f;
								} else
										return _max;
						}
				}

				public float Min {
						get {
				
								if (float.IsNaN (_min)) {
										if (serializedObject != null) {
												if (_fieldMinInfo == null)
														_fieldMinInfo = this.serializedObject.GetType ().GetField (this._fieldNameMin);

												return (float)_fieldMinInfo.GetValue (serializedObject);
										} else
												return 0f;
								} else
										return _min;
						}
				}

				public bool HasEnableToggle {
						get {
								return _hasEnableToggle;
						}
				}

				public bool Enabled {
						get {

								if(_hasEnableToggle)
									if (serializedObject != null) {
											if (_fieldEnabledInfo == null)
													_fieldEnabledInfo = this.serializedObject.GetType ().GetField (this._fieldNameEnabled);
						
											return (bool)_fieldEnabledInfo.GetValue (serializedObject);
									} 

								return _enabled;


						}

						set {
								if (serializedObject != null) {
										_fieldEnabledInfo.SetValue (serializedObject, value);
								}

								_enabled = value;

						}
				}
	
				public object serializedObject;
			
				//
				// Constructors
				//
				public RangeAttributeEx (float min, float max)
				{
						this._min = min;
						this._max = max;
				}

				public RangeAttributeEx (string fieldNameMin, string fieldNameMax, string fieldNameEnabled=null)
				{

						this._fieldNameMin = fieldNameMin;
						this._fieldNameMax = fieldNameMax;
						this._fieldNameEnabled = fieldNameEnabled;

						_hasEnableToggle = !String.IsNullOrEmpty (this._fieldNameEnabled);
						_enabled = !_hasEnableToggle;
				}



		}

		
}

