// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;
using System.Reflection;

namespace ws.winx.unity
{
		public class RangeAttributeEx:PropertyAttribute
		{

				//
				// Fields
				//
				float _max = float.NaN;
				float _min = float.NaN;
				string _fieldNameMax;
				string _fieldNameMin;
				FieldInfo _propertyMaxInfo;
				FieldInfo _propertyMinInfo;

				public float Max {
						get {

								if (float.IsNaN (_max)) {
										if (serializedObject != null) {
												if (_propertyMaxInfo == null)
														_propertyMaxInfo = this.serializedObject.GetType().GetField (this._fieldNameMax);

												return (float)_propertyMaxInfo.GetValue (serializedObject);
										}
										return 1.0f;
								} else
										return _max;
						}
				}

				public float Min {
						get {
				
								if (float.IsNaN (_min)) {
										if (serializedObject != null) {
												if (_propertyMinInfo == null)
														_propertyMinInfo = this.serializedObject.GetType().GetField (this._fieldNameMin);

												return (float)_propertyMinInfo.GetValue (serializedObject);
										} else
												return 0f;
								} else
										return _min;
						}
				}
	
				public object serializedObject;
			
				//
				// Constructors
				//
				public RangeAttributeEx (float min, float max)
				{
						this._min = min;
						this._max = max;
				}

				public RangeAttributeEx (string fieldNameMin, string fieldNameMax)
				{

						this._fieldNameMin = fieldNameMin;
						this._fieldNameMax = fieldNameMax;
				}



		}

		
}

