// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using BehaviourMachine;
using BehaviourMachineEditor;
using UnityEditor;
using UnityEngine;
using ws.winx.bmachine.extensions;

namespace ws.winx.editor.bmachine.extensions
{
		
		public class SendEventNormalizedNodeEditorWindow:EditorWindow
		{
				private static SendEventNormalizedNodeEditorWindow window;
				private static SendEventNormalizedNode node;
				NodeEditor editor;

				

				public static void Show(SendEventNormalizedNode node, Rect position)
				{
								SendEventNormalizedNodeEditorWindow.node = node;
//
			if (SendEventNormalizedNodeEditorWindow.window != null)//restore last 
							position = window.position;

		
			SendEventNormalizedNodeEditorWindow.window =(SendEventNormalizedNodeEditorWindow)EditorWindow.GetWindow(typeof(SendEventNormalizedNodeEditorWindow));
			//EditorWindow.CreateInstance (typeof (SendEventNormalizedEditor));
					//(SendEventNormalizedEditor) 
						SendEventNormalizedNodeEditorWindow.window.position = position;
						SendEventNormalizedNodeEditorWindow.window.Show ();
				}

				public static void Hide ()
				{
						if (window != null)
								window.Close ();
				}

				

				void OnGUI ()
				{
						// The actual window code goes here
						if (SendEventNormalizedNodeEditorWindow.node != null) {
								if (editor == null)
									editor = NodeEditor.CreateEditor(SendEventNormalizedNodeEditorWindow.node.GetType());
								if (editor.target != SendEventNormalizedNodeEditorWindow.node)//How to add target to editor??? or subclass the Node Editor
										editor.DrawNode (SendEventNormalizedNodeEditorWindow.node);
								else
										editor.OnInspectorGUI ();
						}
				
				}

		}
}

