// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEditor;
using BehaviourMachine;
using UnityEngine;
using BehaviourMachineEditor;
using BehaviourMachine;


namespace ws.winx.editor.bmachine.extensions
{
		public class StateEventEditor:EditorWindow
		{
			//
			// Fields
			//
			[VariableInfo (requiredField = false, canBeConstant = false, nullLabel = "Don't Store", tooltip = "Optionally store the delay timer. You can set this value to zero to restart the delay timer. Note: This value is set to zero when the tree is enabled")]
			public FloatVar storeDelayTime;
			
			[VariableInfo (requiredField = false, canBeConstant = false, nullLabel = "Don't Store", tooltip = "Store true if the event was used; false otherwise")]
			public BoolVar storeEventUsed;
			
			[VariableInfo (tooltip = "The event to send")]
			public FsmEvent eventToSend;
			
			[VariableInfo (requiredField = false, nullLabel = "Don't Use", tooltip = "Optional delay in seconds."), Range (0f, 10f)]
			public FloatVar delay;





				public static void Init() {
						var window = EditorWindow.GetWindow<StateEventEditor> ();
								window.position =new Rect(Screen.width/2,Screen.height/2, 250, 50);
						window.Show ();
				}


					void OnGUI () {
						// The actual window code goes here
								NodeEditor editor=NodeEditor.CreateEditor(typeof(SendEvent));
								SendEvent mile=new SendEvent ();
			mile.Reset ();
								editor.DrawNode (mile);
								editor.OnInspectorGUI ();
				
					}

		}
}

