// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Reflection;

namespace ws.winx.unity.attributes
{
		public class AnimatorStateAttribute:PropertyAttribute
		{

				
				public string animatorFieldName;

				public string layerIndexFieldName;





				public AnimatorStateAttribute (string fieldNameAnimator, string fieldNameLayerIndex)
				{
						layerIndexFieldName = fieldNameLayerIndex;

						animatorFieldName = fieldNameAnimator;
				}


		}

		
}

