// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;
using System.Reflection;

namespace ws.winx.unity.attributes
{
		public class MecanimStateInfoAttribute:PropertyAttribute
		{

				Animator _animator;
				FieldInfo _animatorFieldInfo;
				PropertyInfo _animatorPropertyInfo;
				string _fieldNameAnimator;
				public object serializedObject;
				string _fieldNameLayerIndex;

				public int LayerIndex {
						set { 
								serializedObject.GetType ().GetField (_fieldNameLayerIndex).SetValue (serializedObject, value);
						}

				}

				public Animator Ani {
						get {

								if (serializedObject != null && _animator == null) {


										_animatorFieldInfo = serializedObject.GetType ().GetField (_fieldNameAnimator, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);

										if (_animatorFieldInfo == null) { //try if property
												_animatorPropertyInfo = serializedObject.GetType ().GetProperty (_fieldNameAnimator, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
												_animator = (Animator)_animatorPropertyInfo.GetValue (serializedObject, null);
										} else {
												_animator = (Animator)_animatorFieldInfo.GetValue (serializedObject);

										}
								}

								return _animator;
						}
				}

				public MecanimStateInfoAttribute (string fieldNameAnimator, string fieldNameLayerIndex)
				{
						_fieldNameLayerIndex = fieldNameLayerIndex;

						_fieldNameAnimator = fieldNameAnimator;
				}


		}

		
}

